### ISSUE TITLE
World quests are drawing on top of eachother

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#22] opened 2018-07-30 07:52 UTC
**Describe the bug**
World Quests are drawing on top of eachother.

**Do you have an error log of what happened?**
-

**To Reproduce**
Do a world quest in Darkshore, then move on and do another. You will have both worldquests drawn in the tracker at the same position.

**Screenshots**
<img width="110" alt="2018-07-30 15_50_29-world of warcraft" src="https://user-images.githubusercontent.com/26673976/43384359-68029c38-9410-11e8-83a0-5fbea46e9fec.png">

**What is the version of EskaTracker you use ?**
1.0.21

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 223
- Scorpio: 24

**Additional context**

**Comment by ZachieBlade** [comment] 2018-07-31 04:35
+1 https://gyazo.com/011f238b8f1d83789cc391aa64d29055

Does the same for Bonus Objectives.

**Comment by Skamer** [comment] 2018-07-31 19:46
Little question, has the problem appeared recently ?

**Comment by AussieEevee** [comment] 2018-07-31 21:06
Yes. I had it happen just a few minutes ago. As far as I know, everything is up to date.

**Comment by Skamer** [comment] 2018-07-31 23:18
Thank you for the answer.

I have made lot of changes (code level) in the next build for the addon core and its plugin objectives.  In this build, i couldn't reproduce the issue so i assume this has been fixed with all these changes. 

I had initially planned to release the version today but i need to postpone it on tomorrow (Wednesday) in order to be sure nothing has been broken. I don't like to make so much changes in the code between two builds, but here it was needed. 

I'm sorry you encounter these annoying issues, often caused by these major changes.

**Comment by Skamer** [comment] 2018-08-01 18:39
The build is now available. If someone can confirm the issue is well disappeared.

**Comment by AussieEevee** [comment] 2018-08-01 19:44
The issue appears to have disappeared. Thanks.

**Comment by Skamer** [comment] 2018-08-02 21:13
I reopen the ticket because the issue is still there. I got it recently in the Darkshore world quests. I'm investigating on why this occurs.

**Closed** 2018-08-20 15:29 UTC
Labels: Accepted, Bug
