### ISSUE TITLE
Bonus Objectives - multiple empty lines

### ISSUE THREAD

**Issue by AlviSVPP** [Skamer/Eska-Tracker#10] opened 2018-07-21 11:38 UTC
**Describe the bug**
When entering a zone with Bonus Objectives, multiple empty lines can be seen. When clicked on, it opens the Map/Quest Log. 

**To Reproduce**
1. Go to Tanaan Jungle, Throne of Kil'Jaeden for example. 

**Expected behavior**
Only one line should appear per Bonus Objective. 

**Screenshots**
![2018-07-21_13-30-27](https://user-images.githubusercontent.com/41510087/43035182-3e6609d6-8ceb-11e8-87bd-4af3c05b7e71.jpg)

**What is the version of EskaTracker you use ?**
1.0.18 beta

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: v223
- Scorpio: v22

**Comment by Skamer** [comment] 2018-08-02 13:31
It's very hard to reproduce the issue. But with the bug occurred yesteray on the live server concerning quests, i was able to gather some informations about this annoying problem.

Yesterday, when i have changed zone, i was surprised to see that:
![quests_not_appear_issue](https://user-images.githubusercontent.com/849450/43585579-c1f64ee0-9665-11e8-8718-c2bd7d912e21.jpg)

I have lost all my quests caused by Blizzard bug, and EskaTracker displays multiple empty lines. This is here where i  started to understand what's happen about these empty lines.

**What's happen ?** 

The empty lines are in reality the quests you have watched, but for unknown reason this ones has been removed from your quest log without triggered the expected event the addon needs. However, the addon still want update them, but at the moment the informations pulled are no longer valid, so this will create these empty line.


If you encounter the empty lines, thank to check you haven't lost a quest in your quest log. A way to know that is:

1. Right click on the emptly line to open the context menu, then do '[Debug] Info'. 
2. Check the quest id printed in the chat. 
3. Use this quest id and WowHead to know the quest name.
4. Then check  if the quest name is your quest log. If this isn't the case, it's the quest has been removed. 

**Take note, this isn't the fault of EskaTracker if a quest has been removed.**

**Comment by Skamer** [comment] 2018-08-06 14:34
I close it. The issue should now be fixed.

**Closed by Skamer** 2018-08-06 14:34 UTC
Labels: Accepted, Bug, Plugin: Objectives
